### ISSUE TITLE
Element with this selector not found

### ISSUE THREAD

**Issue by monkyver** [IlyaFedotovDev/ckv#1]
Trying to run the basic functionality but get this error although everything is quite normal

import './App.css';
import CKV from "ckv";

const ckVideo = new CKV('.try', './assets/video/video.mp4');
ckVideo.play().then(() => 'do something');

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <div className='try'></div>
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

I get this error:

 Element with this selector not found

      4 | import './App.css';
      5 |
    > 6 | const ckVideo = new CKV('.try', './assets/video/video.mp4');
        |                 ^
      7 | ckVideo.play().then(() => 'do something');
      8 |
      9 | function App() {

Any help appreciated

**Comment by fedonyx** [comment]
Try this please:
```
function App() {
  const savedCKVInstance = useRef()

  useEffect(()=> {
    savedCKVInstance.current = new CKV('.try', './assets/video/video.mp4')

    return () => savedCKVInstance.current.destroy()
  } , [])

}
```
